version: '2'

services:
  mongodb:
    image: mongo
    restart: always

  web:
    build: web
    restart: always
    links:
     - mongodb:mongodb
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - "./web/admin:/var/www/html/admin"
     - "./web/api:/var/www/html/api"
     - "./config/apache2/sites-available:/etc/apache2/sites-available"
     - "./config/apache2/ssl:/etc/apache2/ssl"
