version: '2'

services:
  data:
    image: mongo
    restart: always

  web:
    build: .
    restart: always
    links:
     - data:db
    ports:
     - "8072:80"
    volumes:
     - "./web:/var/www/html"
