version: '2'

services:
  data:
    image: mongo
    restart: always

  webfe:
    build: web
    restart: always
    links:
     - data:db
    volumes:
     - ./web:/var/www/html
    ports:
     - "8071:80"
