version: '2'

services:
  data:
    image: mongo
    restart: always

  webfe:
    build: web/front
    restart: always
    links:
     - data:db
    volumes:
     - ./web/front:/var/www/html
    ports:
     - "8071:80"

  webbe:
    build: web/back
    restart: always
    links:
     - webfe:front
    volumes:
     - ./web/back:/var/www/html
    ports:
     - "8077:80"

