version: '2'

services:
  mongodb:
    image: mongo
    restart: always

  web:
    build: web
    restart: always
    links:
     - mongodb:mongodb
    ports:
     - "8072:80"
    volumes:
     - "./web/admin:/var/www/html/admin"
     - "./web/api:/var/www/html/api"
